#ifndef _THIS_PROJECT_H_
#define _THIS_PROJECT_H_
/* Automatically generated file: do not modify! */
#include "SHESIM_VERSION.h"
#include "ElementsKernel/Version.h"
#define THIS_PROJECT_MAJOR_VERSION SHESIM_MAJOR_VERSION
#define THIS_PROJECT_MINOR_VERSION SHESIM_MINOR_VERSION
#define THIS_PROJECT_PATCH_VERSION SHESIM_PATCH_VERSION
#define THIS_PROJECT_VERSION CALC_ELEMENTS_VERSION(THIS_PROJECT_MAJOR_VERSION,THIS_PROJECT_MINOR_VERSION,THIS_PROJECT_PATCH_VERSION)
#define THIS_PROJECT_VERSION_STRING Elements::getVersionString(THIS_PROJECT_MAJOR_VERSION,THIS_PROJECT_MINOR_VERSION,THIS_PROJECT_PATCH_VERSION)
#define THIS_PROJECT_NAME SheSim
#define THIS_PROJECT_NAME_STRING std::string("SheSim")
#endif
