#ifndef ICEBRG_PHYSICS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_ELEMENTS_VERSION
#define CALC_ELEMENTS_VERSION(maj,min,pat) (((maj) << 32) + ((min) << 16) + (pat))
#endif
#define ICEBRG_PHYSICS_MAJOR_VERSION 1
#define ICEBRG_PHYSICS_MINOR_VERSION 0
#define ICEBRG_PHYSICS_PATCH_VERSION 0
#define ICEBRG_PHYSICS_VERSION CALC_ELEMENTS_VERSION(ICEBRG_PHYSICS_MAJOR_VERSION,ICEBRG_PHYSICS_MINOR_VERSION,ICEBRG_PHYSICS_PATCH_VERSION)
#endif
