# Automatically generated file: do not modify!

from ElementsKernel.Version import getVersionString
from SHESIM_VERSION import SHESIM_MAJOR_VERSION, SHESIM_MINOR_VERSION, SHESIM_PATCH_VERSION
from SHESIM_VERSION import SHESIM_VERSION

THIS_PROJECT_MAJOR_VERSION = SHESIM_MAJOR_VERSION
THIS_PROJECT_MINOR_VERSION = SHESIM_MINOR_VERSION
THIS_PROJECT_PATCH_VERSION = SHESIM_PATCH_VERSION
THIS_PROJECT_VERSION = SHESIM_VERSION
THIS_PROJECT_VERSION_STRING = getVersionString(THIS_PROJECT_MAJOR_VERSION,THIS_PROJECT_MINOR_VERSION,THIS_PROJECT_PATCH_VERSION)
THIS_PROJECT_NAME = "SheSim"
