#ifndef ICEBRG_LENSING_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_ELEMENTS_VERSION
#define CALC_ELEMENTS_VERSION(maj,min,pat) (((maj) << 32) + ((min) << 16) + (pat))
#endif
#define ICEBRG_LENSING_MAJOR_VERSION 1
#define ICEBRG_LENSING_MINOR_VERSION 0
#define ICEBRG_LENSING_PATCH_VERSION 0
#define ICEBRG_LENSING_VERSION CALC_ELEMENTS_VERSION(ICEBRG_LENSING_MAJOR_VERSION,ICEBRG_LENSING_MINOR_VERSION,ICEBRG_LENSING_PATCH_VERSION)
#endif
