#ifndef CICEBRGPY_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_ELEMENTS_VERSION
#define CALC_ELEMENTS_VERSION(maj,min,pat) (((maj) << 32) + ((min) << 16) + (pat))
#endif
#define CICEBRGPY_MAJOR_VERSION 1
#define CICEBRGPY_MINOR_VERSION 0
#define CICEBRGPY_PATCH_VERSION 0
#define CICEBRGPY_VERSION CALC_ELEMENTS_VERSION(CICEBRGPY_MAJOR_VERSION,CICEBRGPY_MINOR_VERSION,CICEBRGPY_PATCH_VERSION)
#endif
